{
 "title": "API Requests",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Requests in Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{app=~\".*-service\",envoy_cluster_name=\"self_admin\"}[30m]) "
    }
   ]
  },
  {
   "title": "Active Requests By Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active{envoy_cluster_name=\"local_agent\"} "
    }
   ]
  },
  {
   "title": "Service Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_external_upstream_rq{consul_full_target=~\".*-service.*\", envoy_response_code =~ '3.*|4.*|5.*'}"
    }
   ]
  },
  {
   "title": "Successfull Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_external_upstream_rq{consul_full_target=~\".*-service.*\", envoy_response_code ='200'}[30s])\n"
    }
   ]
  }
 ]
}